webtalk_init -webtalk_dir /home/fabio/VivadoSources/2017.3/Projects/Didattica/2019/EdgeDetector/EdgeDetector.sim/sim_1/behav/xsim/xsim.dir/top_sim_mealy_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Nov 27 10:40:23 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018833" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174133714_174133715_210667176_105" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "aa87d1405daf5d59a121992eebed4fa5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "3c89f9ae69f14d4aa2e819ae68255358" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 19.04" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "4700.273 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "67.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "119196_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2286200917 -regid "174133714_174133715_210667176_105" -xml /home/fabio/VivadoSources/2017.3/Projects/Didattica/2019/EdgeDetector/EdgeDetector.sim/sim_1/behav/xsim/xsim.dir/top_sim_mealy_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/fabio/VivadoSources/2017.3/Projects/Didattica/2019/EdgeDetector/EdgeDetector.sim/sim_1/behav/xsim/xsim.dir/top_sim_mealy_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/fabio/VivadoSources/2017.3/Projects/Didattica/2019/EdgeDetector/EdgeDetector.sim/sim_1/behav/xsim/xsim.dir/top_sim_mealy_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
